// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run over the DIRECT (non-pooled) connection. Falls back to
    // DATABASE_URL for simple local setups.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
